### PR TITLE
Update to Flink 1.4.1 using the `add-version.sh` script

### PR DESCRIPTION
**Pull request by kppullin**

### CODE REVIEW

**Comment by patricklucas** [comment]
Thanks!

**Comment by kppullin** [comment]
Sure thing!  Any idea on when this might get built and pushed to the docker repo?

**Comment by patricklucas** [comment]
Looks like it's already available. (I requested the update via [this PR](https://github.com/docker-library/official-images/pull/4051))

**Comment by kppullin** [comment]
Ah, wonderful!  Thanks again.

**Pull request merged**
