### PR TITLE
Adding 1.8.2 release

### PR DESCRIPTION
**Pull request by tkaymak**
Adding GPG Key from Jark Wu (E2C45417BED5C104154F341085BACB5AEFAE3202)
Taken from: https://dist.apache.org/repos/dist/release/flink/KEYS

### CODE REVIEW

**Comment by patricklucas** [comment]
Thanks @tkaymak. Please update your PR to have only the change to `add-version.sh`, and we'll regenerate the Dockerfiles as part of deploying the new version.

**Comment by tkaymak** [comment]
@patricklucas done :)

**Comment by patricklucas** [comment]
Thanks!

**Comment by patricklucas** [comment]
https://github.com/docker-library/official-images/pull/6660

**Comment by tkaymak** [comment]
@patricklucas is there a step missing? Seems like this file is still old
https://github.com/docker-library/official-images/blob/master/library/flink

**Pull request merged**
